name: Create Managed Identity
on:
  workflow_dispatch:
    inputs:
      identity-name:
        description: 'User-assigned identity name'
        type: string
        required: true 
      resource-group-name:
        description: 'Resource Group Name'
        type: string
        required: true 

jobs:
  create-identity:
    name: Create identity
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create identity
        id: task-remove-resources
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az identity create -g ${{github.event.inputs.resource-group-name}} -n ${{github.event.inputs.identity-name}}



